# Generated by Django 4.1.5 on 2023-01-22 16:24

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "id",
                    models.CharField(
                        default=user.models.getUUID,
                        editable=False,
                        max_length=200,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "userName",
                    models.CharField(default="null user", max_length=40, unique=True),
                ),
                (
                    "ppiUrl",
                    models.URLField(
                        blank=True, null=True, verbose_name="profile picture url"
                    ),
                ),
                ("is_admin", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
